version: '3'
services:
  test-mongo:
    image: mongo
    container_name: docker-mongo
    ports:
      - "27017:27017"
  muzix-track:
    build: muzix-track/
    restart: always
    container_name: muzix-track
    links:
      - test-mongo
      - config-server
      - eureka-server
    depends_on:
      - test-mongo
      - config-server
    ports:
      - 9089:9089
  config-server:
    build: config-server/
    restart: always
    container_name: config-server
  eureka-server:
    build: eureka-server/
    restart: always
    container_name: eureka-server
    ports:
      - 8091:8091

  apigatewaypattern:
    build: api-gateway-pattern/
    restart: always
    container_name: api-gateway-pattern
    ports:
      - 9099:9099
